repos:
  -   repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v3.2.0
      hooks:
        -   id: check-merge-conflict
        -   id: check-yaml
        -   id: check-toml
        -   id: end-of-file-fixer
        -   id: trailing-whitespace
  -   repo: https://github.com/doublify/pre-commit-rust
      rev: v1.0
      hooks:
        -   id: fmt
        -   id: cargo-check
        -   id: clippy
