[package]
name = "rust_by_example"
version = "0.1.0"
authors = ["Adithya Balaji <adithyabsk@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "hello"
path = "src/hello/hello.rs"

[dependencies]
